-- Seed test data for validation_history demo
-- 24 entities, 5 days of history, 2 system pairs
-- Run with: psql -d postgres -a -f src/app/backend/sql/seed_test_data.sql

-- Truncate tables in reverse dependency order and reset sequences
TRUNCATE control.validation_history RESTART IDENTITY CASCADE;
TRUNCATE control.entity_tags CASCADE;
TRUNCATE control.tags RESTART IDENTITY CASCADE;
TRUNCATE control.schedule_bindings RESTART IDENTITY CASCADE;
TRUNCATE control.triggers RESTART IDENTITY CASCADE;
TRUNCATE control.schedules RESTART IDENTITY CASCADE;
TRUNCATE control.compare_queries RESTART IDENTITY CASCADE;
TRUNCATE control.datasets RESTART IDENTITY CASCADE;
TRUNCATE control.type_transformations RESTART IDENTITY CASCADE;
TRUNCATE control.systems RESTART IDENTITY CASCADE;

-- 1) Systems (only 2 pairs will be used)
INSERT INTO control.systems (id, name, kind, catalog, created_by, updated_by)
VALUES 
  (1, 'warehouse-prod', 'Databricks', 'dw_prod', 'system', 'system'),
  (2, 'analytics-prod', 'Databricks', 'analytics_prod', 'system', 'system'),
  (3, 'reporting-prod', 'Databricks', 'reporting_prod', 'system', 'system'),
  (4, 'crm-legacy', 'Databricks', 'crm_legacy', 'system', 'system');

SELECT setval('control.systems_id_seq', (SELECT MAX(id) FROM control.systems));

-- System Pair 1: analytics-prod (2) -> warehouse-prod (1)
-- System Pair 2: crm-legacy (4) -> reporting-prod (3)

-- 2) Datasets (18 tables)
INSERT INTO control.datasets (id, name, src_system_id, src_schema, src_table, tgt_system_id, tgt_schema, tgt_table, compare_mode, pk_columns, exclude_columns, created_by, updated_by)
VALUES 
  -- System Pair 1 (analytics-prod -> warehouse-prod), primary_key
  (1, 'SALES.ORDERS_FACT', 2, 'SALES', 'ORDERS_FACT', 1, 'SALES', 'ORDERS_FACT', 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'system', 'system'),
  (2, 'SALES.CUSTOMERS_DIM', 2, 'SALES', 'CUSTOMERS_DIM', 1, 'SALES', 'CUSTOMERS_DIM', 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'system', 'system'),
  (3, 'SALES.PRODUCTS_DIM', 2, 'SALES', 'PRODUCTS_DIM', 1, 'SALES', 'PRODUCTS_DIM', 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'system', 'system'),
  (4, 'FINANCE.TRANSACTIONS', 2, 'FINANCE', 'TRANSACTIONS', 1, 'FINANCE', 'TRANSACTIONS', 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'system', 'system'),
  (5, 'FINANCE.ACCOUNTS', 2, 'FINANCE', 'ACCOUNTS', 1, 'FINANCE', 'ACCOUNTS', 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'system', 'system'),
  
  -- System Pair 1 (analytics-prod -> warehouse-prod), except_all
  (6, 'INVENTORY.STOCK_LEVELS', 2, 'INVENTORY', 'STOCK_LEVELS', 1, 'INVENTORY', 'STOCK_LEVELS', 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'system', 'system'),
  (7, 'INVENTORY.WAREHOUSES', 2, 'INVENTORY', 'WAREHOUSES', 1, 'INVENTORY', 'WAREHOUSES', 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'system', 'system'),
  (8, 'MARKETING.CAMPAIGNS', 2, 'MARKETING', 'CAMPAIGNS', 1, 'MARKETING', 'CAMPAIGNS', 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'system', 'system'),
  (9, 'MARKETING.LEADS', 2, 'MARKETING', 'LEADS', 1, 'MARKETING', 'LEADS', 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'system', 'system'),
  
  -- System Pair 2 (crm-legacy -> reporting-prod), primary_key
  (10, 'HR.EMPLOYEES', 4, 'HR', 'EMPLOYEES', 3, 'HR', 'EMPLOYEES', 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'system', 'system'),
  (11, 'HR.DEPARTMENTS', 4, 'HR', 'DEPARTMENTS', 3, 'HR', 'DEPARTMENTS', 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'system', 'system'),
  (12, 'HR.PAYROLL', 4, 'HR', 'PAYROLL', 3, 'HR', 'PAYROLL', 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'system', 'system'),
  (13, 'SUPPORT.TICKETS', 4, 'SUPPORT', 'TICKETS', 3, 'SUPPORT', 'TICKETS', 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'system', 'system'),
  (14, 'SUPPORT.AGENTS', 4, 'SUPPORT', 'AGENTS', 3, 'SUPPORT', 'AGENTS', 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'system', 'system'),
  
  -- System Pair 2 (crm-legacy -> reporting-prod), except_all
  (15, 'CRM.CONTACTS', 4, 'CRM', 'CONTACTS', 3, 'CRM', 'CONTACTS', 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'system', 'system'),
  (16, 'CRM.OPPORTUNITIES', 4, 'CRM', 'OPPORTUNITIES', 3, 'CRM', 'OPPORTUNITIES', 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'system', 'system'),
  (17, 'CRM.ACCOUNTS', 4, 'CRM', 'ACCOUNTS', 3, 'CRM', 'ACCOUNTS', 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'system', 'system'),
  (18, 'LOGISTICS.SHIPMENTS', 4, 'LOGISTICS', 'SHIPMENTS', 3, 'LOGISTICS', 'SHIPMENTS', 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'system', 'system');

SELECT setval('control.datasets_id_seq', (SELECT MAX(id) FROM control.datasets));

-- 3) Compare Queries (6 queries)
INSERT INTO control.compare_queries (id, name, src_system_id, tgt_system_id, sql, compare_mode, pk_columns, created_by, updated_by)
VALUES
  -- System Pair 1, primary_key
  (1, 'Daily Revenue Summary', 2, 1, 'SELECT date_key, SUM(revenue) as total FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], 'system', 'system'),
  (2, 'Product Performance', 2, 1, 'SELECT product_id, SUM(units_sold) as total FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], 'system', 'system'),
  (3, 'Monthly Financials', 2, 1, 'SELECT month_key, SUM(amount) as total FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], 'system', 'system'),
  
  -- System Pair 2, except_all
  (4, 'Customer Churn Analysis', 4, 3, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], 'system', 'system'),
  (5, 'Support Metrics', 4, 3, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], 'system', 'system'),
  (6, 'Employee Headcount', 4, 3, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], 'system', 'system');

SELECT setval('control.compare_queries_id_seq', (SELECT MAX(id) FROM control.compare_queries));

-- 4) Tags
-- Compare mode tags
INSERT INTO control.tags (name) VALUES ('primary_key'), ('except_all');
-- Domain tags (4 domains, mutually exclusive)
INSERT INTO control.tags (name) VALUES ('sales'), ('finance'), ('hr'), ('operations');
-- Subcategory tags (no overlap between domains)
-- sales: retail, wholesale, ecommerce
-- finance: accounting, treasury
-- hr: recruiting, payroll, benefits
-- operations: logistics, inventory, support
INSERT INTO control.tags (name) VALUES 
  ('retail'), ('wholesale'), ('ecommerce'),
  ('accounting'), ('treasury'),
  ('recruiting'), ('payroll'), ('benefits'),
  ('logistics'), ('inventory'), ('support');

-- 5) Tag associations
-- ================================================================================
-- Compare mode tags (primary_key vs except_all)
-- ================================================================================
-- primary_key: tables 1-5, 10-14, queries 1-3
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 1, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 2, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 3, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 4, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 5, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 10, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 11, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 12, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 13, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 14, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 1, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 2, id FROM control.tags WHERE name = 'primary_key';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 3, id FROM control.tags WHERE name = 'primary_key';

-- except_all: tables 6-9, 15-18, queries 4-6
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 6, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 7, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 8, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 9, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 15, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 16, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 17, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 18, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 4, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 5, id FROM control.tags WHERE name = 'except_all';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 6, id FROM control.tags WHERE name = 'except_all';

-- ================================================================================
-- Domain tags (6 entities each, mutually exclusive)
-- ================================================================================
-- sales (6): tables 1,2,3,8,9 + query 1
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 1, id FROM control.tags WHERE name = 'sales';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 2, id FROM control.tags WHERE name = 'sales';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 3, id FROM control.tags WHERE name = 'sales';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 8, id FROM control.tags WHERE name = 'sales';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 9, id FROM control.tags WHERE name = 'sales';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 1, id FROM control.tags WHERE name = 'sales';

-- finance (6): tables 4,5,16,17 + queries 2,3
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 4, id FROM control.tags WHERE name = 'finance';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 5, id FROM control.tags WHERE name = 'finance';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 16, id FROM control.tags WHERE name = 'finance';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 17, id FROM control.tags WHERE name = 'finance';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 2, id FROM control.tags WHERE name = 'finance';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 3, id FROM control.tags WHERE name = 'finance';

-- hr (6): tables 10,11,12 + queries 4,5,6
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 10, id FROM control.tags WHERE name = 'hr';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 11, id FROM control.tags WHERE name = 'hr';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 12, id FROM control.tags WHERE name = 'hr';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 4, id FROM control.tags WHERE name = 'hr';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 5, id FROM control.tags WHERE name = 'hr';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 6, id FROM control.tags WHERE name = 'hr';

-- operations (6): tables 6,7,13,14,15,18
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 6, id FROM control.tags WHERE name = 'operations';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 7, id FROM control.tags WHERE name = 'operations';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 13, id FROM control.tags WHERE name = 'operations';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 14, id FROM control.tags WHERE name = 'operations';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 15, id FROM control.tags WHERE name = 'operations';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 18, id FROM control.tags WHERE name = 'operations';

-- ================================================================================
-- Subcategory tags (unique to each domain)
-- ================================================================================
-- sales subcategories: retail, wholesale, ecommerce
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 1, id FROM control.tags WHERE name = 'retail';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 2, id FROM control.tags WHERE name = 'retail';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 3, id FROM control.tags WHERE name = 'wholesale';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 1, id FROM control.tags WHERE name = 'wholesale';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 8, id FROM control.tags WHERE name = 'ecommerce';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 9, id FROM control.tags WHERE name = 'ecommerce';

-- finance subcategories: accounting, treasury
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 4, id FROM control.tags WHERE name = 'accounting';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 16, id FROM control.tags WHERE name = 'accounting';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 2, id FROM control.tags WHERE name = 'accounting';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 5, id FROM control.tags WHERE name = 'treasury';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 17, id FROM control.tags WHERE name = 'treasury';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 3, id FROM control.tags WHERE name = 'treasury';

-- hr subcategories: recruiting, payroll, benefits
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 10, id FROM control.tags WHERE name = 'recruiting';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 5, id FROM control.tags WHERE name = 'recruiting';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 11, id FROM control.tags WHERE name = 'payroll';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 12, id FROM control.tags WHERE name = 'payroll';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 4, id FROM control.tags WHERE name = 'benefits';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'query', 6, id FROM control.tags WHERE name = 'benefits';

-- operations subcategories: logistics, inventory, support
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 7, id FROM control.tags WHERE name = 'logistics';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 18, id FROM control.tags WHERE name = 'logistics';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 6, id FROM control.tags WHERE name = 'inventory';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 15, id FROM control.tags WHERE name = 'inventory';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 13, id FROM control.tags WHERE name = 'support';
INSERT INTO control.entity_tags (entity_type, entity_id, tag_id) SELECT 'table', 14, id FROM control.tags WHERE name = 'support';

-- 6) Validation history - using a function to generate records efficiently
-- Helper: Create validation history entries

INSERT INTO control.validation_history (
  trigger_id, entity_type, entity_id, entity_name, source, schedule_id,
  requested_by, requested_at, started_at, finished_at,
  source_system_id, target_system_id, source_system_name, target_system_name,
  source_table, target_table, sql_query, compare_mode, pk_columns, exclude_columns,
  status, schema_match, schema_details, row_count_source, row_count_target, row_count_match,
  rows_compared, rows_matched, rows_different, sample_differences,
  error_message, error_details, databricks_run_id, databricks_run_url, full_result, created_at
) VALUES 

-- ============================================================================
-- DAY 1 (4 days ago) - Worst day: ~20% success, many errors
-- ============================================================================

-- Tables 1-9: System Pair 1 (analytics-prod -> warehouse-prod)
(1001, 'table', 1, 'SALES.ORDERS_FACT', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 20s', NOW()-INTERVAL'4d'+INTERVAL'8h 50s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.ORDERS_FACT', 'SALES.ORDERS_FACT', NULL, 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Connection timeout to source', '{"type":"ConnectionError"}'::jsonb, 'r1001', 'https://db.com/r1001', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 50s'),
(1002, 'table', 2, 'SALES.CUSTOMERS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 15s', NOW()-INTERVAL'4d'+INTERVAL'8h 35s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.CUSTOMERS_DIM', 'SALES.CUSTOMERS_DIM', NULL, 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["CUSTOMER_ID","NAME","EMAIL","REGION"],"columns_missing":[],"columns_extra":[]}'::jsonb, 50000, 49000, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":1000,"summary":[{"name":"CUSTOMER_ID","type":"numeric","is_pk":true,"min":49001,"max":50000,"nulls":0},{"name":"NAME","type":"string","is_pk":false,"cardinality":998,"nulls":0},{"name":"EMAIL","type":"string","is_pk":false,"cardinality":1000,"nulls":2},{"name":"REGION","type":"string","is_pk":false,"cardinality":4,"nulls":0}],"samples":[{"CUSTOMER_ID":49001,"NAME":"John Smith","EMAIL":"john.smith@example.com","REGION":"APAC"},{"CUSTOMER_ID":49002,"NAME":"Jane Doe","EMAIL":"jane.doe@example.com","REGION":"EMEA"},{"CUSTOMER_ID":49003,"NAME":"Bob Wilson","EMAIL":null,"REGION":"AMER"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r1002', 'https://db.com/r1002', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 35s'),
(1003, 'table', 3, 'SALES.PRODUCTS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 10s', NOW()-INTERVAL'4d'+INTERVAL'8h 25s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.PRODUCTS_DIM', 'SALES.PRODUCTS_DIM', NULL, 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["PRODUCT_ID","NAME"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10000, 10000, true, 10000, 9500, 500, '[{"PRODUCT_ID":"P001"}]'::jsonb, NULL, '{}'::jsonb, 'r1003', 'https://db.com/r1003', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 25s'),
(1004, 'table', 4, 'FINANCE.TRANSACTIONS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 30s', NOW()-INTERVAL'4d'+INTERVAL'8h 90s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.TRANSACTIONS', 'FINANCE.TRANSACTIONS', NULL, 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Spark cluster terminated', '{"type":"ClusterError"}'::jsonb, 'r1004', 'https://db.com/r1004', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 90s'),
(1005, 'table', 5, 'FINANCE.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 12s', NOW()-INTERVAL'4d'+INTERVAL'8h 28s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.ACCOUNTS', 'FINANCE.ACCOUNTS', NULL, 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'failed', true, '{"columns_matched":["ACCOUNT_ID","ACCOUNT_NAME","BALANCE","STATUS"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25000, 24500, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":500,"summary":[{"name":"ACCOUNT_ID","type":"string","is_pk":true,"cardinality":500,"nulls":0},{"name":"ACCOUNT_NAME","type":"string","is_pk":false,"cardinality":495,"nulls":0},{"name":"BALANCE","type":"numeric","is_pk":false,"min":-5000.00,"max":150000.00,"nulls":0},{"name":"STATUS","type":"string","is_pk":false,"cardinality":3,"nulls":0}],"samples":[{"ACCOUNT_ID":"ACC-24501","ACCOUNT_NAME":"Acme Corp","BALANCE":45000.00,"STATUS":"active"},{"ACCOUNT_ID":"ACC-24502","ACCOUNT_NAME":"Global Inc","BALANCE":-1200.00,"STATUS":"overdue"},{"ACCOUNT_ID":"ACC-24503","ACCOUNT_NAME":"Tech Ltd","BALANCE":78500.00,"STATUS":"active"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r1005', 'https://db.com/r1005', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 28s'),
(1006, 'table', 6, 'INVENTORY.STOCK_LEVELS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 8s', NOW()-INTERVAL'4d'+INTERVAL'8h 22s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.STOCK_LEVELS', 'INVENTORY.STOCK_LEVELS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'failed', true, '{"columns_matched":["SKU","QTY"],"columns_missing":[],"columns_extra":[]}'::jsonb, 75000, 75000, true, 75000, 74000, 1000, '[{"SKU":"S001"}]'::jsonb, NULL, '{}'::jsonb, 'r1006', 'https://db.com/r1006', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 22s'),
(1007, 'table', 7, 'INVENTORY.WAREHOUSES', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 5s', NOW()-INTERVAL'4d'+INTERVAL'8h 12s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.WAREHOUSES', 'INVENTORY.WAREHOUSES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["WH_ID","NAME"],"columns_missing":[],"columns_extra":[]}'::jsonb, 50, 50, true, 50, 50, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r1007', 'https://db.com/r1007', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 12s'),
(1008, 'table', 8, 'MARKETING.CAMPAIGNS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 6s', NOW()-INTERVAL'4d'+INTERVAL'8h 15s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.CAMPAIGNS', 'MARKETING.CAMPAIGNS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'failed', true, '{"columns_matched":["CAMPAIGN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 500, 480, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r1008', 'https://db.com/r1008', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 15s'),
(1009, 'table', 9, 'MARKETING.LEADS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'8h', NOW()-INTERVAL'4d'+INTERVAL'8h 7s', NOW()-INTERVAL'4d'+INTERVAL'8h 18s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.LEADS', 'MARKETING.LEADS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SQL syntax error', '{"type":"SQLError"}'::jsonb, 'r1009', 'https://db.com/r1009', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'8h 18s'),

-- Tables 10-18: System Pair 2 (crm-legacy -> reporting-prod)
(1010, 'table', 10, 'HR.EMPLOYEES', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 10s', NOW()-INTERVAL'4d'+INTERVAL'9h 25s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.EMPLOYEES', 'HR.EMPLOYEES', NULL, 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'failed', true, '{"columns_matched":["EMPLOYEE_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 12000, 12000, true, 12000, 11500, 500, '[{"EMPLOYEE_ID":"E001"}]'::jsonb, NULL, '{}'::jsonb, 'r1010', 'https://db.com/r1010', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 25s'),
(1011, 'table', 11, 'HR.DEPARTMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 5s', NOW()-INTERVAL'4d'+INTERVAL'9h 12s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.DEPARTMENTS', 'HR.DEPARTMENTS', NULL, 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["DEPT_ID","NAME"],"columns_missing":[],"columns_extra":[]}'::jsonb, 50, 50, true, 50, 50, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r1011', 'https://db.com/r1011', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 12s'),
(1012, 'table', 12, 'HR.PAYROLL', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 15s', NOW()-INTERVAL'4d'+INTERVAL'9h 45s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.PAYROLL', 'HR.PAYROLL', NULL, 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'failed', true, '{"columns_matched":["PAYROLL_ID","EMPLOYEE_ID","AMOUNT","PAY_DATE"],"columns_missing":[],"columns_extra":[]}'::jsonb, 144000, 143000, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":1000,"summary":[{"name":"PAYROLL_ID","type":"numeric","is_pk":true,"min":143001,"max":144000,"nulls":0},{"name":"EMPLOYEE_ID","type":"string","is_pk":false,"cardinality":850,"nulls":0},{"name":"AMOUNT","type":"numeric","is_pk":false,"min":2100.00,"max":15000.00,"nulls":0},{"name":"PAY_DATE","type":"time","is_pk":false,"min":"2025-01-01","max":"2025-01-15","nulls":0}],"samples":[{"PAYROLL_ID":143001,"EMPLOYEE_ID":"E5001","AMOUNT":4500.00,"PAY_DATE":"2025-01-15"},{"PAYROLL_ID":143002,"EMPLOYEE_ID":"E5002","AMOUNT":6200.00,"PAY_DATE":"2025-01-15"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r1012', 'https://db.com/r1012', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 45s'),
(1013, 'table', 13, 'SUPPORT.TICKETS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 8s', NOW()-INTERVAL'4d'+INTERVAL'9h 20s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.TICKETS', 'SUPPORT.TICKETS', NULL, 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Authentication failed', '{"type":"AuthError"}'::jsonb, 'r1013', 'https://db.com/r1013', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 20s'),
(1014, 'table', 14, 'SUPPORT.AGENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 4s', NOW()-INTERVAL'4d'+INTERVAL'9h 10s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.AGENTS', 'SUPPORT.AGENTS', NULL, 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'failed', true, '{"columns_matched":["AGENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 200, 200, true, 200, 180, 20, '[{"AGENT_ID":"A001"}]'::jsonb, NULL, '{}'::jsonb, 'r1014', 'https://db.com/r1014', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 10s'),
(1015, 'table', 15, 'CRM.CONTACTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 12s', NOW()-INTERVAL'4d'+INTERVAL'9h 30s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.CONTACTS', 'CRM.CONTACTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'failed', true, '{"columns_matched":["CONTACT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 100000, 99000, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r1015', 'https://db.com/r1015', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 30s'),
(1016, 'table', 16, 'CRM.OPPORTUNITIES', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 10s', NOW()-INTERVAL'4d'+INTERVAL'9h 28s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.OPPORTUNITIES', 'CRM.OPPORTUNITIES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'failed', true, '{"columns_matched":["OPP_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25000, 25000, true, 25000, 24000, 1000, '[{"OPP_ID":"O001"}]'::jsonb, NULL, '{}'::jsonb, 'r1016', 'https://db.com/r1016', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 28s'),
(1017, 'table', 17, 'CRM.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 6s', NOW()-INTERVAL'4d'+INTERVAL'9h 15s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.ACCOUNTS', 'CRM.ACCOUNTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15000, 15000, true, 15000, 15000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r1017', 'https://db.com/r1017', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 15s'),
(1018, 'table', 18, 'LOGISTICS.SHIPMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'9h', NOW()-INTERVAL'4d'+INTERVAL'9h 20s', NOW()-INTERVAL'4d'+INTERVAL'9h 50s', 4, 3, 'crm-legacy', 'reporting-prod', 'LOGISTICS.SHIPMENTS', 'LOGISTICS.SHIPMENTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Network timeout', '{"type":"NetworkError"}'::jsonb, 'r1018', 'https://db.com/r1018', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'9h 50s'),

-- Queries Day 1
(1019, 'compare_query', 1, 'Daily Revenue Summary', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 10s', NOW()-INTERVAL'4d'+INTERVAL'10h 30s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT date_key, SUM(revenue) FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["date_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 365, 365, true, 365, 360, 5, '[{"date_key":"2025-01-01"}]'::jsonb, NULL, '{}'::jsonb, 'r1019', 'https://db.com/r1019', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 30s'),
(1020, 'compare_query', 2, 'Product Performance', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 8s', NOW()-INTERVAL'4d'+INTERVAL'10h 22s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT product_id, SUM(units_sold) FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], ARRAY[]::TEXT[], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Query timeout', '{"type":"TimeoutError"}'::jsonb, 'r1020', 'https://db.com/r1020', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 22s'),
(1021, 'compare_query', 3, 'Monthly Financials', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 12s', NOW()-INTERVAL'4d'+INTERVAL'10h 35s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT month_key, SUM(amount) FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["month_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 22, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":2,"summary":[{"name":"month_key","type":"string","is_pk":true,"cardinality":2,"nulls":0},{"name":"total","type":"numeric","is_pk":false,"min":980000.00,"max":1150000.00,"nulls":0}],"samples":[{"month_key":"2024-11","total":1150000.00},{"month_key":"2024-12","total":980000.00}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r1021', 'https://db.com/r1021', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 35s'),
(1022, 'compare_query', 4, 'Customer Churn Analysis', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 15s', NOW()-INTERVAL'4d'+INTERVAL'10h 40s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["segment","churn_flag","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 20, 4, '[{"segment":"Enterprise"}]'::jsonb, NULL, '{}'::jsonb, 'r1022', 'https://db.com/r1022', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 40s'),
(1023, 'compare_query', 5, 'Support Metrics', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 5s', NOW()-INTERVAL'4d'+INTERVAL'10h 15s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["queue","avg"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10, 10, true, 10, 10, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r1023', 'https://db.com/r1023', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 15s'),
(1024, 'compare_query', 6, 'Employee Headcount', 'schedule', NULL, 'system', NOW()-INTERVAL'4d'+INTERVAL'10h', NOW()-INTERVAL'4d'+INTERVAL'10h 6s', NOW()-INTERVAL'4d'+INTERVAL'10h 16s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["department","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15, 14, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r1024', 'https://db.com/r1024', '{}'::jsonb, NOW()-INTERVAL'4d'+INTERVAL'10h 16s'),

-- ============================================================================
-- DAY 2 (3 days ago) - Improving: ~35% success
-- ============================================================================

(2001, 'table', 1, 'SALES.ORDERS_FACT', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 25s', NOW()-INTERVAL'3d'+INTERVAL'8h 60s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.ORDERS_FACT', 'SALES.ORDERS_FACT', NULL, 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["ORDER_ID","LINE_ITEM_ID","PRODUCT_ID","QTY","PRICE"],"columns_missing":[],"columns_extra":[]}'::jsonb, 151000, 150500, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":500,"summary":[{"name":"ORDER_ID","type":"numeric","is_pk":true,"min":150001,"max":150500,"nulls":0},{"name":"LINE_ITEM_ID","type":"numeric","is_pk":true,"min":1,"max":5,"nulls":0},{"name":"PRODUCT_ID","type":"string","is_pk":false,"cardinality":120,"nulls":0},{"name":"QTY","type":"numeric","is_pk":false,"min":1,"max":50,"nulls":0},{"name":"PRICE","type":"numeric","is_pk":false,"min":5.99,"max":299.99,"nulls":0}],"samples":[{"ORDER_ID":150001,"LINE_ITEM_ID":1,"PRODUCT_ID":"P1001","QTY":2,"PRICE":49.99},{"ORDER_ID":150001,"LINE_ITEM_ID":2,"PRODUCT_ID":"P1002","QTY":1,"PRICE":129.99},{"ORDER_ID":150002,"LINE_ITEM_ID":1,"PRODUCT_ID":"P1003","QTY":5,"PRICE":9.99}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r2001', 'https://db.com/r2001', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 60s'),
(2002, 'table', 2, 'SALES.CUSTOMERS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 15s', NOW()-INTERVAL'3d'+INTERVAL'8h 32s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.CUSTOMERS_DIM', 'SALES.CUSTOMERS_DIM', NULL, 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["CUSTOMER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 50500, 50500, true, 50500, 50500, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2002', 'https://db.com/r2002', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 32s'),
(2003, 'table', 3, 'SALES.PRODUCTS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 10s', NOW()-INTERVAL'3d'+INTERVAL'8h 22s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.PRODUCTS_DIM', 'SALES.PRODUCTS_DIM', NULL, 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["PRODUCT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10100, 10100, true, 10100, 9800, 300, '[{"PRODUCT_ID":"P100"}]'::jsonb, NULL, '{}'::jsonb, 'r2003', 'https://db.com/r2003', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 22s'),
(2004, 'table', 4, 'FINANCE.TRANSACTIONS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 30s', NOW()-INTERVAL'3d'+INTERVAL'8h 85s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.TRANSACTIONS', 'FINANCE.TRANSACTIONS', NULL, 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'failed', true, '{"columns_matched":["TXN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 2510000, 2510000, true, 2510000, 2509500, 500, '[{"TXN_ID":"T001"}]'::jsonb, NULL, '{}'::jsonb, 'r2004', 'https://db.com/r2004', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 85s'),
(2005, 'table', 5, 'FINANCE.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 12s', NOW()-INTERVAL'3d'+INTERVAL'8h 26s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.ACCOUNTS', 'FINANCE.ACCOUNTS', NULL, 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25200, 25200, true, 25200, 25200, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2005', 'https://db.com/r2005', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 26s'),
(2006, 'table', 6, 'INVENTORY.STOCK_LEVELS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 8s', NOW()-INTERVAL'3d'+INTERVAL'8h 20s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.STOCK_LEVELS', 'INVENTORY.STOCK_LEVELS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'failed', true, '{"columns_matched":["SKU"],"columns_missing":[],"columns_extra":[]}'::jsonb, 76000, 75500, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r2006', 'https://db.com/r2006', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 20s'),
(2007, 'table', 7, 'INVENTORY.WAREHOUSES', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 5s', NOW()-INTERVAL'3d'+INTERVAL'8h 11s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.WAREHOUSES', 'INVENTORY.WAREHOUSES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["WH_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 52, 52, true, 52, 52, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2007', 'https://db.com/r2007', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 11s'),
(2008, 'table', 8, 'MARKETING.CAMPAIGNS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 6s', NOW()-INTERVAL'3d'+INTERVAL'8h 14s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.CAMPAIGNS', 'MARKETING.CAMPAIGNS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'failed', true, '{"columns_matched":["CAMPAIGN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 510, 510, true, 510, 500, 10, '[{"CAMPAIGN_ID":"C001"}]'::jsonb, NULL, '{}'::jsonb, 'r2008', 'https://db.com/r2008', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 14s'),
(2009, 'table', 9, 'MARKETING.LEADS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'8h', NOW()-INTERVAL'3d'+INTERVAL'8h 7s', NOW()-INTERVAL'3d'+INTERVAL'8h 16s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.LEADS', 'MARKETING.LEADS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'succeeded', true, '{"columns_matched":["LEAD_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 8500, 8500, true, 8500, 8500, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2009', 'https://db.com/r2009', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'8h 16s'),
(2010, 'table', 10, 'HR.EMPLOYEES', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 10s', NOW()-INTERVAL'3d'+INTERVAL'9h 24s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.EMPLOYEES', 'HR.EMPLOYEES', NULL, 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'failed', true, '{"columns_matched":["EMPLOYEE_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 12050, 12050, true, 12050, 11800, 250, '[{"EMPLOYEE_ID":"E050"}]'::jsonb, NULL, '{}'::jsonb, 'r2010', 'https://db.com/r2010', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 24s'),
(2011, 'table', 11, 'HR.DEPARTMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 5s', NOW()-INTERVAL'3d'+INTERVAL'9h 11s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.DEPARTMENTS', 'HR.DEPARTMENTS', NULL, 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["DEPT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 52, 52, true, 52, 52, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2011', 'https://db.com/r2011', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 11s'),
(2012, 'table', 12, 'HR.PAYROLL', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 15s', NOW()-INTERVAL'3d'+INTERVAL'9h 42s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.PAYROLL', 'HR.PAYROLL', NULL, 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'failed', true, '{"columns_matched":["PAYROLL_ID","EMPLOYEE_ID","AMOUNT","PAY_DATE"],"columns_missing":[],"columns_extra":[]}'::jsonb, 144500, 144000, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":500,"summary":[{"name":"PAYROLL_ID","type":"numeric","is_pk":true,"min":144001,"max":144500,"nulls":0},{"name":"EMPLOYEE_ID","type":"string","is_pk":false,"cardinality":420,"nulls":0},{"name":"AMOUNT","type":"numeric","is_pk":false,"min":2200.00,"max":14500.00,"nulls":0},{"name":"PAY_DATE","type":"time","is_pk":false,"min":"2025-01-16","max":"2025-01-20","nulls":0}],"samples":[{"PAYROLL_ID":144001,"EMPLOYEE_ID":"E6001","AMOUNT":5100.00,"PAY_DATE":"2025-01-20"},{"PAYROLL_ID":144002,"EMPLOYEE_ID":"E6002","AMOUNT":7300.00,"PAY_DATE":"2025-01-20"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r2012', 'https://db.com/r2012', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 42s'),
(2013, 'table', 13, 'SUPPORT.TICKETS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 8s', NOW()-INTERVAL'3d'+INTERVAL'9h 18s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.TICKETS', 'SUPPORT.TICKETS', NULL, 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'succeeded', true, '{"columns_matched":["TICKET_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 5200, 5200, true, 5200, 5200, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2013', 'https://db.com/r2013', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 18s'),
(2014, 'table', 14, 'SUPPORT.AGENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 4s', NOW()-INTERVAL'3d'+INTERVAL'9h 9s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.AGENTS', 'SUPPORT.AGENTS', NULL, 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'failed', true, '{"columns_matched":["AGENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 205, 205, true, 205, 195, 10, '[{"AGENT_ID":"A010"}]'::jsonb, NULL, '{}'::jsonb, 'r2014', 'https://db.com/r2014', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 9s'),
(2015, 'table', 15, 'CRM.CONTACTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 12s', NOW()-INTERVAL'3d'+INTERVAL'9h 28s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.CONTACTS', 'CRM.CONTACTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Memory exceeded', '{"type":"MemoryError"}'::jsonb, 'r2015', 'https://db.com/r2015', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 28s'),
(2016, 'table', 16, 'CRM.OPPORTUNITIES', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 10s', NOW()-INTERVAL'3d'+INTERVAL'9h 26s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.OPPORTUNITIES', 'CRM.OPPORTUNITIES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'failed', true, '{"columns_matched":["OPP_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25500, 25500, true, 25500, 25000, 500, '[{"OPP_ID":"O100"}]'::jsonb, NULL, '{}'::jsonb, 'r2016', 'https://db.com/r2016', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 26s'),
(2017, 'table', 17, 'CRM.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 6s', NOW()-INTERVAL'3d'+INTERVAL'9h 14s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.ACCOUNTS', 'CRM.ACCOUNTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15200, 15200, true, 15200, 15200, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2017', 'https://db.com/r2017', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 14s'),
(2018, 'table', 18, 'LOGISTICS.SHIPMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'9h', NOW()-INTERVAL'3d'+INTERVAL'9h 20s', NOW()-INTERVAL'3d'+INTERVAL'9h 48s', 4, 3, 'crm-legacy', 'reporting-prod', 'LOGISTICS.SHIPMENTS', 'LOGISTICS.SHIPMENTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'failed', true, '{"columns_matched":["SHIPMENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 85000, 84500, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r2018', 'https://db.com/r2018', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'9h 48s'),
(2019, 'compare_query', 1, 'Daily Revenue Summary', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 10s', NOW()-INTERVAL'3d'+INTERVAL'10h 28s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT date_key, SUM(revenue) FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["date_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 366, 366, true, 366, 366, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2019', 'https://db.com/r2019', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 28s'),
(2020, 'compare_query', 2, 'Product Performance', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 8s', NOW()-INTERVAL'3d'+INTERVAL'10h 20s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT product_id, SUM(units_sold) FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["product_id","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10100, 10100, true, 10100, 10000, 100, '[{"product_id":"P500"}]'::jsonb, NULL, '{}'::jsonb, 'r2020', 'https://db.com/r2020', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 20s'),
(2021, 'compare_query', 3, 'Monthly Financials', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 12s', NOW()-INTERVAL'3d'+INTERVAL'10h 32s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT month_key, SUM(amount) FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["month_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 23, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":1,"summary":[{"name":"month_key","type":"string","is_pk":true,"cardinality":1,"nulls":0},{"name":"total","type":"numeric","is_pk":false,"min":1050000.00,"max":1050000.00,"nulls":0}],"samples":[{"month_key":"2024-12","total":1050000.00}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r2021', 'https://db.com/r2021', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 32s'),
(2022, 'compare_query', 4, 'Customer Churn Analysis', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 15s', NOW()-INTERVAL'3d'+INTERVAL'10h 38s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["segment","churn_flag","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 24, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2022', 'https://db.com/r2022', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 38s'),
(2023, 'compare_query', 5, 'Support Metrics', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 5s', NOW()-INTERVAL'3d'+INTERVAL'10h 14s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["queue","avg"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10, 10, true, 10, 9, 1, '[{"queue":"Tier2"}]'::jsonb, NULL, '{}'::jsonb, 'r2023', 'https://db.com/r2023', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 14s'),
(2024, 'compare_query', 6, 'Employee Headcount', 'schedule', NULL, 'system', NOW()-INTERVAL'3d'+INTERVAL'10h', NOW()-INTERVAL'3d'+INTERVAL'10h 6s', NOW()-INTERVAL'3d'+INTERVAL'10h 15s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["department","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15, 15, true, 15, 15, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r2024', 'https://db.com/r2024', '{}'::jsonb, NOW()-INTERVAL'3d'+INTERVAL'10h 15s'),

-- ============================================================================
-- DAY 3 (2 days ago) - Better: ~55% success
-- ============================================================================

(3001, 'table', 1, 'SALES.ORDERS_FACT', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 25s', NOW()-INTERVAL'2d'+INTERVAL'8h 58s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.ORDERS_FACT', 'SALES.ORDERS_FACT', NULL, 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["ORDER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 152000, 152000, true, 152000, 152000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3001', 'https://db.com/r3001', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 58s'),
(3002, 'table', 2, 'SALES.CUSTOMERS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 14s', NOW()-INTERVAL'2d'+INTERVAL'8h 30s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.CUSTOMERS_DIM', 'SALES.CUSTOMERS_DIM', NULL, 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["CUSTOMER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 51000, 51000, true, 51000, 51000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3002', 'https://db.com/r3002', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 30s'),
(3003, 'table', 3, 'SALES.PRODUCTS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 10s', NOW()-INTERVAL'2d'+INTERVAL'8h 21s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.PRODUCTS_DIM', 'SALES.PRODUCTS_DIM', NULL, 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["PRODUCT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10200, 10200, true, 10200, 10100, 100, '[{"PRODUCT_ID":"P200"}]'::jsonb, NULL, '{}'::jsonb, 'r3003', 'https://db.com/r3003', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 21s'),
(3004, 'table', 4, 'FINANCE.TRANSACTIONS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 30s', NOW()-INTERVAL'2d'+INTERVAL'8h 82s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.TRANSACTIONS', 'FINANCE.TRANSACTIONS', NULL, 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'succeeded', true, '{"columns_matched":["TXN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 2520000, 2520000, true, 2520000, 2520000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3004', 'https://db.com/r3004', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 82s'),
(3005, 'table', 5, 'FINANCE.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 12s', NOW()-INTERVAL'2d'+INTERVAL'8h 25s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.ACCOUNTS', 'FINANCE.ACCOUNTS', NULL, 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25400, 25400, true, 25400, 25400, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3005', 'https://db.com/r3005', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 25s'),
(3006, 'table', 6, 'INVENTORY.STOCK_LEVELS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 8s', NOW()-INTERVAL'2d'+INTERVAL'8h 19s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.STOCK_LEVELS', 'INVENTORY.STOCK_LEVELS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'failed', true, '{"columns_matched":["SKU"],"columns_missing":[],"columns_extra":[]}'::jsonb, 77000, 77000, true, 77000, 76800, 200, '[{"SKU":"S200"}]'::jsonb, NULL, '{}'::jsonb, 'r3006', 'https://db.com/r3006', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 19s'),
(3007, 'table', 7, 'INVENTORY.WAREHOUSES', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 5s', NOW()-INTERVAL'2d'+INTERVAL'8h 10s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.WAREHOUSES', 'INVENTORY.WAREHOUSES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["WH_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 53, 53, true, 53, 53, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3007', 'https://db.com/r3007', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 10s'),
(3008, 'table', 8, 'MARKETING.CAMPAIGNS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 6s', NOW()-INTERVAL'2d'+INTERVAL'8h 13s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.CAMPAIGNS', 'MARKETING.CAMPAIGNS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'succeeded', true, '{"columns_matched":["CAMPAIGN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 520, 520, true, 520, 520, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3008', 'https://db.com/r3008', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 13s'),
(3009, 'table', 9, 'MARKETING.LEADS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'8h', NOW()-INTERVAL'2d'+INTERVAL'8h 7s', NOW()-INTERVAL'2d'+INTERVAL'8h 15s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.LEADS', 'MARKETING.LEADS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'failed', true, '{"columns_matched":["LEAD_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 8800, 8700, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r3009', 'https://db.com/r3009', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'8h 15s'),
(3010, 'table', 10, 'HR.EMPLOYEES', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 10s', NOW()-INTERVAL'2d'+INTERVAL'9h 23s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.EMPLOYEES', 'HR.EMPLOYEES', NULL, 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'succeeded', true, '{"columns_matched":["EMPLOYEE_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 12100, 12100, true, 12100, 12100, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3010', 'https://db.com/r3010', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 23s'),
(3011, 'table', 11, 'HR.DEPARTMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 5s', NOW()-INTERVAL'2d'+INTERVAL'9h 10s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.DEPARTMENTS', 'HR.DEPARTMENTS', NULL, 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["DEPT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 53, 53, true, 53, 53, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3011', 'https://db.com/r3011', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 10s'),
(3012, 'table', 12, 'HR.PAYROLL', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 15s', NOW()-INTERVAL'2d'+INTERVAL'9h 40s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.PAYROLL', 'HR.PAYROLL', NULL, 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'failed', true, '{"columns_matched":["PAYROLL_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 145000, 145000, true, 145000, 144500, 500, '[{"PAYROLL_ID":"P500"}]'::jsonb, NULL, '{}'::jsonb, 'r3012', 'https://db.com/r3012', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 40s'),
(3013, 'table', 13, 'SUPPORT.TICKETS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 8s', NOW()-INTERVAL'2d'+INTERVAL'9h 17s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.TICKETS', 'SUPPORT.TICKETS', NULL, 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'succeeded', true, '{"columns_matched":["TICKET_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 5300, 5300, true, 5300, 5300, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3013', 'https://db.com/r3013', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 17s'),
(3014, 'table', 14, 'SUPPORT.AGENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 4s', NOW()-INTERVAL'2d'+INTERVAL'9h 9s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.AGENTS', 'SUPPORT.AGENTS', NULL, 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'succeeded', true, '{"columns_matched":["AGENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 208, 208, true, 208, 208, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3014', 'https://db.com/r3014', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 9s'),
(3015, 'table', 15, 'CRM.CONTACTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 12s', NOW()-INTERVAL'2d'+INTERVAL'9h 27s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.CONTACTS', 'CRM.CONTACTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'failed', true, '{"columns_matched":["CONTACT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 102000, 101500, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r3015', 'https://db.com/r3015', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 27s'),
(3016, 'table', 16, 'CRM.OPPORTUNITIES', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 10s', NOW()-INTERVAL'2d'+INTERVAL'9h 24s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.OPPORTUNITIES', 'CRM.OPPORTUNITIES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'succeeded', true, '{"columns_matched":["OPP_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 26000, 26000, true, 26000, 26000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3016', 'https://db.com/r3016', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 24s'),
(3017, 'table', 17, 'CRM.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 6s', NOW()-INTERVAL'2d'+INTERVAL'9h 13s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.ACCOUNTS', 'CRM.ACCOUNTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'failed', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15400, 15400, true, 15400, 15300, 100, '[{"ACCOUNT_ID":"A100"}]'::jsonb, NULL, '{}'::jsonb, 'r3017', 'https://db.com/r3017', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 13s'),
(3018, 'table', 18, 'LOGISTICS.SHIPMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'9h', NOW()-INTERVAL'2d'+INTERVAL'9h 20s', NOW()-INTERVAL'2d'+INTERVAL'9h 46s', 4, 3, 'crm-legacy', 'reporting-prod', 'LOGISTICS.SHIPMENTS', 'LOGISTICS.SHIPMENTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'succeeded', true, '{"columns_matched":["SHIPMENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 86000, 86000, true, 86000, 86000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3018', 'https://db.com/r3018', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'9h 46s'),
(3019, 'compare_query', 1, 'Daily Revenue Summary', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 10s', NOW()-INTERVAL'2d'+INTERVAL'10h 26s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT date_key, SUM(revenue) FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["date_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 367, 367, true, 367, 367, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3019', 'https://db.com/r3019', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 26s'),
(3020, 'compare_query', 2, 'Product Performance', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 8s', NOW()-INTERVAL'2d'+INTERVAL'10h 19s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT product_id, SUM(units_sold) FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["product_id","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10200, 10200, true, 10200, 10200, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3020', 'https://db.com/r3020', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 19s'),
(3021, 'compare_query', 3, 'Monthly Financials', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 12s', NOW()-INTERVAL'2d'+INTERVAL'10h 30s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT month_key, SUM(amount) FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["month_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 23, 1, '[{"month_key":"2025-12"}]'::jsonb, NULL, '{}'::jsonb, 'r3021', 'https://db.com/r3021', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 30s'),
(3022, 'compare_query', 4, 'Customer Churn Analysis', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 15s', NOW()-INTERVAL'2d'+INTERVAL'10h 36s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["segment","churn_flag","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 24, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3022', 'https://db.com/r3022', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 36s'),
(3023, 'compare_query', 5, 'Support Metrics', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 5s', NOW()-INTERVAL'2d'+INTERVAL'10h 13s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["queue","avg"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10, 10, true, 10, 10, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r3023', 'https://db.com/r3023', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 13s'),
(3024, 'compare_query', 6, 'Employee Headcount', 'schedule', NULL, 'system', NOW()-INTERVAL'2d'+INTERVAL'10h', NOW()-INTERVAL'2d'+INTERVAL'10h 6s', NOW()-INTERVAL'2d'+INTERVAL'10h 14s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["department","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15, 14, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r3024', 'https://db.com/r3024', '{}'::jsonb, NOW()-INTERVAL'2d'+INTERVAL'10h 14s'),

-- ============================================================================
-- DAY 4 (1 day ago / yesterday) - Good: ~75% success
-- ============================================================================

(4001, 'table', 1, 'SALES.ORDERS_FACT', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 24s', NOW()-INTERVAL'1d'+INTERVAL'8h 55s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.ORDERS_FACT', 'SALES.ORDERS_FACT', NULL, 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["ORDER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 153000, 153000, true, 153000, 153000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4001', 'https://db.com/r4001', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 55s'),
(4002, 'table', 2, 'SALES.CUSTOMERS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 13s', NOW()-INTERVAL'1d'+INTERVAL'8h 28s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.CUSTOMERS_DIM', 'SALES.CUSTOMERS_DIM', NULL, 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["CUSTOMER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 51500, 51500, true, 51500, 51500, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4002', 'https://db.com/r4002', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 28s'),
(4003, 'table', 3, 'SALES.PRODUCTS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 10s', NOW()-INTERVAL'1d'+INTERVAL'8h 20s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.PRODUCTS_DIM', 'SALES.PRODUCTS_DIM', NULL, 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["PRODUCT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10300, 10300, true, 10300, 10300, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4003', 'https://db.com/r4003', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 20s'),
(4004, 'table', 4, 'FINANCE.TRANSACTIONS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 30s', NOW()-INTERVAL'1d'+INTERVAL'8h 78s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.TRANSACTIONS', 'FINANCE.TRANSACTIONS', NULL, 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'succeeded', true, '{"columns_matched":["TXN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 2530000, 2530000, true, 2530000, 2530000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4004', 'https://db.com/r4004', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 78s'),
(4005, 'table', 5, 'FINANCE.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 12s', NOW()-INTERVAL'1d'+INTERVAL'8h 24s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.ACCOUNTS', 'FINANCE.ACCOUNTS', NULL, 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25600, 25600, true, 25600, 25600, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4005', 'https://db.com/r4005', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 24s'),
(4006, 'table', 6, 'INVENTORY.STOCK_LEVELS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 8s', NOW()-INTERVAL'1d'+INTERVAL'8h 18s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.STOCK_LEVELS', 'INVENTORY.STOCK_LEVELS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'succeeded', true, '{"columns_matched":["SKU"],"columns_missing":[],"columns_extra":[]}'::jsonb, 78000, 78000, true, 78000, 78000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4006', 'https://db.com/r4006', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 18s'),
(4007, 'table', 7, 'INVENTORY.WAREHOUSES', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 5s', NOW()-INTERVAL'1d'+INTERVAL'8h 10s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.WAREHOUSES', 'INVENTORY.WAREHOUSES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["WH_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 54, 54, true, 54, 54, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4007', 'https://db.com/r4007', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 10s'),
(4008, 'table', 8, 'MARKETING.CAMPAIGNS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 6s', NOW()-INTERVAL'1d'+INTERVAL'8h 12s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.CAMPAIGNS', 'MARKETING.CAMPAIGNS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'succeeded', true, '{"columns_matched":["CAMPAIGN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 525, 525, true, 525, 525, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4008', 'https://db.com/r4008', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 12s'),
(4009, 'table', 9, 'MARKETING.LEADS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'8h', NOW()-INTERVAL'1d'+INTERVAL'8h 7s', NOW()-INTERVAL'1d'+INTERVAL'8h 14s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.LEADS', 'MARKETING.LEADS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'failed', true, '{"columns_matched":["LEAD_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 9100, 9100, true, 9100, 9050, 50, '[{"LEAD_ID":"L050"}]'::jsonb, NULL, '{}'::jsonb, 'r4009', 'https://db.com/r4009', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'8h 14s'),
(4010, 'table', 10, 'HR.EMPLOYEES', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 10s', NOW()-INTERVAL'1d'+INTERVAL'9h 22s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.EMPLOYEES', 'HR.EMPLOYEES', NULL, 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'succeeded', true, '{"columns_matched":["EMPLOYEE_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 12150, 12150, true, 12150, 12150, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4010', 'https://db.com/r4010', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 22s'),
(4011, 'table', 11, 'HR.DEPARTMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 5s', NOW()-INTERVAL'1d'+INTERVAL'9h 10s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.DEPARTMENTS', 'HR.DEPARTMENTS', NULL, 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["DEPT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 54, 54, true, 54, 54, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4011', 'https://db.com/r4011', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 10s'),
(4012, 'table', 12, 'HR.PAYROLL', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 15s', NOW()-INTERVAL'1d'+INTERVAL'9h 38s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.PAYROLL', 'HR.PAYROLL', NULL, 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'succeeded', true, '{"columns_matched":["PAYROLL_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 145500, 145500, true, 145500, 145500, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4012', 'https://db.com/r4012', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 38s'),
(4013, 'table', 13, 'SUPPORT.TICKETS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 8s', NOW()-INTERVAL'1d'+INTERVAL'9h 16s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.TICKETS', 'SUPPORT.TICKETS', NULL, 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'failed', true, '{"columns_matched":["TICKET_ID","CUSTOMER_ID","SUBJECT","PRIORITY","STATUS"],"columns_missing":[],"columns_extra":[]}'::jsonb, 5400, 5350, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":50,"summary":[{"name":"TICKET_ID","type":"string","is_pk":true,"cardinality":50,"nulls":0},{"name":"CUSTOMER_ID","type":"numeric","is_pk":false,"min":1001,"max":9500,"nulls":0},{"name":"SUBJECT","type":"string","is_pk":false,"cardinality":48,"nulls":0},{"name":"PRIORITY","type":"string","is_pk":false,"cardinality":3,"nulls":0},{"name":"STATUS","type":"string","is_pk":false,"cardinality":2,"nulls":0}],"samples":[{"TICKET_ID":"TKT-5351","CUSTOMER_ID":4521,"SUBJECT":"Login issue","PRIORITY":"high","STATUS":"open"},{"TICKET_ID":"TKT-5352","CUSTOMER_ID":7834,"SUBJECT":"Billing question","PRIORITY":"medium","STATUS":"open"},{"TICKET_ID":"TKT-5353","CUSTOMER_ID":2156,"SUBJECT":"Feature request","PRIORITY":"low","STATUS":"pending"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r4013', 'https://db.com/r4013', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 16s'),
(4014, 'table', 14, 'SUPPORT.AGENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 4s', NOW()-INTERVAL'1d'+INTERVAL'9h 8s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.AGENTS', 'SUPPORT.AGENTS', NULL, 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'succeeded', true, '{"columns_matched":["AGENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 210, 210, true, 210, 210, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4014', 'https://db.com/r4014', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 8s'),
(4015, 'table', 15, 'CRM.CONTACTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 12s', NOW()-INTERVAL'1d'+INTERVAL'9h 26s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.CONTACTS', 'CRM.CONTACTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'succeeded', true, '{"columns_matched":["CONTACT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 103000, 103000, true, 103000, 103000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4015', 'https://db.com/r4015', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 26s'),
(4016, 'table', 16, 'CRM.OPPORTUNITIES', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 10s', NOW()-INTERVAL'1d'+INTERVAL'9h 23s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.OPPORTUNITIES', 'CRM.OPPORTUNITIES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'failed', true, '{"columns_matched":["OPP_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 26500, 26500, true, 26500, 26400, 100, '[{"OPP_ID":"O200"}]'::jsonb, NULL, '{}'::jsonb, 'r4016', 'https://db.com/r4016', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 23s'),
(4017, 'table', 17, 'CRM.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 6s', NOW()-INTERVAL'1d'+INTERVAL'9h 12s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.ACCOUNTS', 'CRM.ACCOUNTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15600, 15600, true, 15600, 15600, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4017', 'https://db.com/r4017', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 12s'),
(4018, 'table', 18, 'LOGISTICS.SHIPMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'9h', NOW()-INTERVAL'1d'+INTERVAL'9h 20s', NOW()-INTERVAL'1d'+INTERVAL'9h 44s', 4, 3, 'crm-legacy', 'reporting-prod', 'LOGISTICS.SHIPMENTS', 'LOGISTICS.SHIPMENTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'failed', true, '{"columns_matched":["SHIPMENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 87000, 86800, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r4018', 'https://db.com/r4018', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'9h 44s'),
(4019, 'compare_query', 1, 'Daily Revenue Summary', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 10s', NOW()-INTERVAL'1d'+INTERVAL'10h 24s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT date_key, SUM(revenue) FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["date_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 368, 368, true, 368, 368, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4019', 'https://db.com/r4019', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 24s'),
(4020, 'compare_query', 2, 'Product Performance', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 8s', NOW()-INTERVAL'1d'+INTERVAL'10h 18s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT product_id, SUM(units_sold) FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["product_id","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10300, 10300, true, 10300, 10300, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4020', 'https://db.com/r4020', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 18s'),
(4021, 'compare_query', 3, 'Monthly Financials', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 12s', NOW()-INTERVAL'1d'+INTERVAL'10h 28s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT month_key, SUM(amount) FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["month_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 24, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4021', 'https://db.com/r4021', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 28s'),
(4022, 'compare_query', 4, 'Customer Churn Analysis', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 15s', NOW()-INTERVAL'1d'+INTERVAL'10h 34s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["segment","churn_flag","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 24, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4022', 'https://db.com/r4022', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 34s'),
(4023, 'compare_query', 5, 'Support Metrics', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 5s', NOW()-INTERVAL'1d'+INTERVAL'10h 12s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["queue","avg"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10, 10, true, 10, 10, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r4023', 'https://db.com/r4023', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 12s'),
(4024, 'compare_query', 6, 'Employee Headcount', 'schedule', NULL, 'system', NOW()-INTERVAL'1d'+INTERVAL'10h', NOW()-INTERVAL'1d'+INTERVAL'10h 6s', NOW()-INTERVAL'1d'+INTERVAL'10h 13s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["department","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15, 15, true, 15, 14, 1, '[{"department":"IT"}]'::jsonb, NULL, '{}'::jsonb, 'r4024', 'https://db.com/r4024', '{}'::jsonb, NOW()-INTERVAL'1d'+INTERVAL'10h 13s'),

-- ============================================================================
-- DAY 5 (Today) - Mixed results to show all statuses well-represented
-- ~50% success, ~20% row count fail, ~20% diff fail, ~10% error
-- ============================================================================

-- Successes (12 entities)
(5001, 'table', 1, 'SALES.ORDERS_FACT', 'schedule', NULL, 'system', NOW()-INTERVAL'6h', NOW()-INTERVAL'6h'+INTERVAL'22s', NOW()-INTERVAL'6h'+INTERVAL'52s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.ORDERS_FACT', 'SALES.ORDERS_FACT', NULL, 'primary_key', ARRAY['ORDER_ID','LINE_ITEM_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["ORDER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 154000, 154000, true, 154000, 154000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5001', 'https://db.com/r5001', '{}'::jsonb, NOW()-INTERVAL'6h'+INTERVAL'52s'),
(5002, 'table', 2, 'SALES.CUSTOMERS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'5h 30m', NOW()-INTERVAL'5h 30m'+INTERVAL'12s', NOW()-INTERVAL'5h 30m'+INTERVAL'26s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.CUSTOMERS_DIM', 'SALES.CUSTOMERS_DIM', NULL, 'primary_key', ARRAY['CUSTOMER_ID'], ARRAY['ETL_LOAD_TS'], 'succeeded', true, '{"columns_matched":["CUSTOMER_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 52000, 52000, true, 52000, 52000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5002', 'https://db.com/r5002', '{}'::jsonb, NOW()-INTERVAL'5h 30m'+INTERVAL'26s'),
(5003, 'table', 5, 'FINANCE.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'5h', NOW()-INTERVAL'5h'+INTERVAL'10s', NOW()-INTERVAL'5h'+INTERVAL'22s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.ACCOUNTS', 'FINANCE.ACCOUNTS', NULL, 'primary_key', ARRAY['ACCOUNT_ID'], ARRAY['MODIFIED_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 25800, 25800, true, 25800, 25800, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5003', 'https://db.com/r5003', '{}'::jsonb, NOW()-INTERVAL'5h'+INTERVAL'22s'),
(5004, 'table', 7, 'INVENTORY.WAREHOUSES', 'schedule', NULL, 'system', NOW()-INTERVAL'4h 30m', NOW()-INTERVAL'4h 30m'+INTERVAL'4s', NOW()-INTERVAL'4h 30m'+INTERVAL'9s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.WAREHOUSES', 'INVENTORY.WAREHOUSES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["WH_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 55, 55, true, 55, 55, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5004', 'https://db.com/r5004', '{}'::jsonb, NOW()-INTERVAL'4h 30m'+INTERVAL'9s'),
(5005, 'table', 10, 'HR.EMPLOYEES', 'schedule', NULL, 'system', NOW()-INTERVAL'4h', NOW()-INTERVAL'4h'+INTERVAL'9s', NOW()-INTERVAL'4h'+INTERVAL'20s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.EMPLOYEES', 'HR.EMPLOYEES', NULL, 'primary_key', ARRAY['EMPLOYEE_ID'], ARRAY['LAST_LOGIN'], 'succeeded', true, '{"columns_matched":["EMPLOYEE_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 12200, 12200, true, 12200, 12200, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5005', 'https://db.com/r5005', '{}'::jsonb, NOW()-INTERVAL'4h'+INTERVAL'20s'),
(5006, 'table', 11, 'HR.DEPARTMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3h 30m', NOW()-INTERVAL'3h 30m'+INTERVAL'4s', NOW()-INTERVAL'3h 30m'+INTERVAL'9s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.DEPARTMENTS', 'HR.DEPARTMENTS', NULL, 'primary_key', ARRAY['DEPT_ID'], ARRAY['UPDATED_AT'], 'succeeded', true, '{"columns_matched":["DEPT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 55, 55, true, 55, 55, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5006', 'https://db.com/r5006', '{}'::jsonb, NOW()-INTERVAL'3h 30m'+INTERVAL'9s'),
(5007, 'table', 14, 'SUPPORT.AGENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'3h', NOW()-INTERVAL'3h'+INTERVAL'4s', NOW()-INTERVAL'3h'+INTERVAL'8s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.AGENTS', 'SUPPORT.AGENTS', NULL, 'primary_key', ARRAY['AGENT_ID'], ARRAY['LOGIN_TS'], 'succeeded', true, '{"columns_matched":["AGENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 212, 212, true, 212, 212, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5007', 'https://db.com/r5007', '{}'::jsonb, NOW()-INTERVAL'3h'+INTERVAL'8s'),
(5008, 'table', 15, 'CRM.CONTACTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2h 30m', NOW()-INTERVAL'2h 30m'+INTERVAL'11s', NOW()-INTERVAL'2h 30m'+INTERVAL'24s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.CONTACTS', 'CRM.CONTACTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['LAST_ACTIVITY'], 'succeeded', true, '{"columns_matched":["CONTACT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 104000, 104000, true, 104000, 104000, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5008', 'https://db.com/r5008', '{}'::jsonb, NOW()-INTERVAL'2h 30m'+INTERVAL'24s'),
(5009, 'table', 17, 'CRM.ACCOUNTS', 'schedule', NULL, 'system', NOW()-INTERVAL'2h', NOW()-INTERVAL'2h'+INTERVAL'5s', NOW()-INTERVAL'2h'+INTERVAL'11s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.ACCOUNTS', 'CRM.ACCOUNTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SYNC_TS'], 'succeeded', true, '{"columns_matched":["ACCOUNT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 15800, 15800, true, 15800, 15800, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5009', 'https://db.com/r5009', '{}'::jsonb, NOW()-INTERVAL'2h'+INTERVAL'11s'),
(5010, 'compare_query', 1, 'Daily Revenue Summary', 'schedule', NULL, 'system', NOW()-INTERVAL'1h 30m', NOW()-INTERVAL'1h 30m'+INTERVAL'9s', NOW()-INTERVAL'1h 30m'+INTERVAL'22s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT date_key, SUM(revenue) FROM sales.daily GROUP BY date_key', 'primary_key', ARRAY['date_key'], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["date_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 369, 369, true, 369, 369, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5010', 'https://db.com/r5010', '{}'::jsonb, NOW()-INTERVAL'1h 30m'+INTERVAL'22s'),
(5011, 'compare_query', 4, 'Customer Churn Analysis', 'schedule', NULL, 'system', NOW()-INTERVAL'1h', NOW()-INTERVAL'1h'+INTERVAL'14s', NOW()-INTERVAL'1h'+INTERVAL'32s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT segment, churn_flag, COUNT(*) FROM crm.churn GROUP BY 1,2', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["segment","churn_flag","count"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 24, true, 24, 24, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5011', 'https://db.com/r5011', '{}'::jsonb, NOW()-INTERVAL'1h'+INTERVAL'32s'),
(5012, 'compare_query', 5, 'Support Metrics', 'schedule', NULL, 'system', NOW()-INTERVAL'45m', NOW()-INTERVAL'45m'+INTERVAL'4s', NOW()-INTERVAL'45m'+INTERVAL'11s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT queue, AVG(resolution_time) FROM support.metrics GROUP BY queue', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'succeeded', true, '{"columns_matched":["queue","avg"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10, 10, true, 10, 10, 0, '[]'::jsonb, NULL, '{}'::jsonb, 'r5012', 'https://db.com/r5012', '{}'::jsonb, NOW()-INTERVAL'45m'+INTERVAL'11s'),

-- Row Count Failures (5 entities) - with PK count analysis for primary_key mode
(5013, 'table', 3, 'SALES.PRODUCTS_DIM', 'schedule', NULL, 'system', NOW()-INTERVAL'5h 15m', NOW()-INTERVAL'5h 15m'+INTERVAL'9s', NOW()-INTERVAL'5h 15m'+INTERVAL'19s', 2, 1, 'analytics-prod', 'warehouse-prod', 'SALES.PRODUCTS_DIM', 'SALES.PRODUCTS_DIM', NULL, 'primary_key', ARRAY['PRODUCT_ID'], ARRAY['ETL_LOAD_TS'], 'failed', true, '{"columns_matched":["PRODUCT_ID","NAME","CATEGORY","PRICE"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10500, 10400, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":100,"summary":[{"name":"PRODUCT_ID","type":"string","is_pk":true,"cardinality":100,"nulls":0},{"name":"NAME","type":"string","is_pk":false,"cardinality":98,"nulls":0},{"name":"CATEGORY","type":"string","is_pk":false,"cardinality":5,"nulls":2},{"name":"PRICE","type":"numeric","is_pk":false,"min":9.99,"max":499.99,"nulls":0},{"name":"CREATED_AT","type":"time","is_pk":false,"min":"2025-01-15T08:00:00","max":"2025-01-20T16:30:00","nulls":0}],"samples":[{"PRODUCT_ID":"P10401","NAME":"Widget Pro X","CATEGORY":"Electronics","PRICE":149.99,"CREATED_AT":"2025-01-20T14:30:00"},{"PRODUCT_ID":"P10402","NAME":"Gadget Plus","CATEGORY":"Electronics","PRICE":79.99,"CREATED_AT":"2025-01-20T15:00:00"},{"PRODUCT_ID":"P10403","NAME":"Tool Set Basic","CATEGORY":"Tools","PRICE":29.99,"CREATED_AT":"2025-01-20T15:30:00"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r5013', 'https://db.com/r5013', '{}'::jsonb, NOW()-INTERVAL'5h 15m'+INTERVAL'19s'),
(5014, 'table', 8, 'MARKETING.CAMPAIGNS', 'schedule', NULL, 'system', NOW()-INTERVAL'4h 15m', NOW()-INTERVAL'4h 15m'+INTERVAL'5s', NOW()-INTERVAL'4h 15m'+INTERVAL'12s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.CAMPAIGNS', 'MARKETING.CAMPAIGNS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['INTERNAL_NOTES'], 'failed', true, '{"columns_matched":["CAMPAIGN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 540, 530, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r5014', 'https://db.com/r5014', '{}'::jsonb, NOW()-INTERVAL'4h 15m'+INTERVAL'12s'),
(5015, 'table', 12, 'HR.PAYROLL', 'schedule', NULL, 'system', NOW()-INTERVAL'3h 45m', NOW()-INTERVAL'3h 45m'+INTERVAL'14s', NOW()-INTERVAL'3h 45m'+INTERVAL'35s', 4, 3, 'crm-legacy', 'reporting-prod', 'HR.PAYROLL', 'HR.PAYROLL', NULL, 'primary_key', ARRAY['PAYROLL_ID'], ARRAY['PROCESSED_AT'], 'failed', true, '{"columns_matched":["PAYROLL_ID","EMPLOYEE_ID","AMOUNT","PAY_DATE"],"columns_missing":[],"columns_extra":[]}'::jsonb, 146000, 145800, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":200,"summary":[{"name":"PAYROLL_ID","type":"numeric","is_pk":true,"min":145801,"max":146000,"nulls":0},{"name":"EMPLOYEE_ID","type":"string","is_pk":false,"cardinality":180,"nulls":0},{"name":"AMOUNT","type":"numeric","is_pk":false,"min":2500.00,"max":12500.00,"nulls":0},{"name":"PAY_DATE","type":"time","is_pk":false,"min":"2025-01-15","max":"2025-01-20","nulls":0},{"name":"STATUS","type":"string","is_pk":false,"cardinality":2,"nulls":0}],"samples":[{"PAYROLL_ID":145995,"EMPLOYEE_ID":"E1234","AMOUNT":5500.00,"PAY_DATE":"2025-01-20","STATUS":"pending"},{"PAYROLL_ID":145996,"EMPLOYEE_ID":"E1235","AMOUNT":4200.00,"PAY_DATE":"2025-01-20","STATUS":"pending"},{"PAYROLL_ID":145997,"EMPLOYEE_ID":"E1236","AMOUNT":6800.00,"PAY_DATE":"2025-01-20","STATUS":"approved"}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r5015', 'https://db.com/r5015', '{}'::jsonb, NOW()-INTERVAL'3h 45m'+INTERVAL'35s'),
(5016, 'table', 18, 'LOGISTICS.SHIPMENTS', 'schedule', NULL, 'system', NOW()-INTERVAL'1h 45m', NOW()-INTERVAL'1h 45m'+INTERVAL'18s', NOW()-INTERVAL'1h 45m'+INTERVAL'42s', 4, 3, 'crm-legacy', 'reporting-prod', 'LOGISTICS.SHIPMENTS', 'LOGISTICS.SHIPMENTS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['TRACKING_UPDATE'], 'failed', true, '{"columns_matched":["SHIPMENT_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 88000, 87500, false, NULL, NULL, NULL, NULL, NULL, '{}'::jsonb, 'r5016', 'https://db.com/r5016', '{}'::jsonb, NOW()-INTERVAL'1h 45m'+INTERVAL'42s'),
(5017, 'compare_query', 3, 'Monthly Financials', 'schedule', NULL, 'system', NOW()-INTERVAL'1h 15m', NOW()-INTERVAL'1h 15m'+INTERVAL'11s', NOW()-INTERVAL'1h 15m'+INTERVAL'27s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT month_key, SUM(amount) FROM finance.monthly GROUP BY month_key', 'primary_key', ARRAY['month_key'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["month_key","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 24, 23, false, NULL, NULL, NULL, '{"mode":"row_count_mismatch","skipped":false,"missing_in_target":{"count":1,"summary":[{"name":"month_key","type":"string","is_pk":true,"cardinality":1,"nulls":0},{"name":"total","type":"numeric","is_pk":false,"min":1250000.50,"max":1250000.50,"nulls":0}],"samples":[{"month_key":"2025-01","total":1250000.50}]},"missing_in_source":{"count":0,"summary":[],"samples":[]}}'::jsonb, NULL, '{}'::jsonb, 'r5017', 'https://db.com/r5017', '{}'::jsonb, NOW()-INTERVAL'1h 15m'+INTERVAL'27s'),

-- Diff Failures (5 entities)
(5018, 'table', 4, 'FINANCE.TRANSACTIONS', 'schedule', NULL, 'system', NOW()-INTERVAL'4h 45m', NOW()-INTERVAL'4h 45m'+INTERVAL'28s', NOW()-INTERVAL'4h 45m'+INTERVAL'75s', 2, 1, 'analytics-prod', 'warehouse-prod', 'FINANCE.TRANSACTIONS', 'FINANCE.TRANSACTIONS', NULL, 'primary_key', ARRAY['TXN_ID'], ARRAY['CREATED_TS'], 'failed', true, '{"columns_matched":["TXN_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 2540000, 2540000, true, 2540000, 2539000, 1000, '[{"TXN_ID":"T5001"}]'::jsonb, NULL, '{}'::jsonb, 'r5018', 'https://db.com/r5018', '{}'::jsonb, NOW()-INTERVAL'4h 45m'+INTERVAL'75s'),
(5019, 'table', 6, 'INVENTORY.STOCK_LEVELS', 'schedule', NULL, 'system', NOW()-INTERVAL'4h', NOW()-INTERVAL'4h'+INTERVAL'7s', NOW()-INTERVAL'4h'+INTERVAL'17s', 2, 1, 'analytics-prod', 'warehouse-prod', 'INVENTORY.STOCK_LEVELS', 'INVENTORY.STOCK_LEVELS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['SNAPSHOT_TS'], 'failed', true, '{"columns_matched":["SKU"],"columns_missing":[],"columns_extra":[]}'::jsonb, 79000, 79000, true, 79000, 78500, 500, '[{"SKU":"S500"}]'::jsonb, NULL, '{}'::jsonb, 'r5019', 'https://db.com/r5019', '{}'::jsonb, NOW()-INTERVAL'4h'+INTERVAL'17s'),
(5020, 'table', 13, 'SUPPORT.TICKETS', 'schedule', NULL, 'system', NOW()-INTERVAL'3h 15m', NOW()-INTERVAL'3h 15m'+INTERVAL'7s', NOW()-INTERVAL'3h 15m'+INTERVAL'15s', 4, 3, 'crm-legacy', 'reporting-prod', 'SUPPORT.TICKETS', 'SUPPORT.TICKETS', NULL, 'primary_key', ARRAY['TICKET_ID'], ARRAY['RESOLVED_DATE'], 'failed', true, '{"columns_matched":["TICKET_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 5500, 5500, true, 5500, 5450, 50, '[{"TICKET_ID":"T5050"}]'::jsonb, NULL, '{}'::jsonb, 'r5020', 'https://db.com/r5020', '{}'::jsonb, NOW()-INTERVAL'3h 15m'+INTERVAL'15s'),
(5021, 'table', 16, 'CRM.OPPORTUNITIES', 'schedule', NULL, 'system', NOW()-INTERVAL'2h 15m', NOW()-INTERVAL'2h 15m'+INTERVAL'9s', NOW()-INTERVAL'2h 15m'+INTERVAL'22s', 4, 3, 'crm-legacy', 'reporting-prod', 'CRM.OPPORTUNITIES', 'CRM.OPPORTUNITIES', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['MODIFIED_DATE'], 'failed', true, '{"columns_matched":["OPP_ID"],"columns_missing":[],"columns_extra":[]}'::jsonb, 27000, 27000, true, 27000, 26900, 100, '[{"OPP_ID":"O300"}]'::jsonb, NULL, '{}'::jsonb, 'r5021', 'https://db.com/r5021', '{}'::jsonb, NOW()-INTERVAL'2h 15m'+INTERVAL'22s'),
(5022, 'compare_query', 2, 'Product Performance', 'schedule', NULL, 'system', NOW()-INTERVAL'1h', NOW()-INTERVAL'1h'+INTERVAL'7s', NOW()-INTERVAL'1h'+INTERVAL'17s', 2, 1, 'analytics-prod', 'warehouse-prod', NULL, NULL, 'SELECT product_id, SUM(units_sold) FROM sales.performance GROUP BY product_id', 'primary_key', ARRAY['product_id'], ARRAY[]::TEXT[], 'failed', true, '{"columns_matched":["product_id","total"],"columns_missing":[],"columns_extra":[]}'::jsonb, 10400, 10400, true, 10400, 10350, 50, '[{"product_id":"P600"}]'::jsonb, NULL, '{}'::jsonb, 'r5022', 'https://db.com/r5022', '{}'::jsonb, NOW()-INTERVAL'1h'+INTERVAL'17s'),

-- Errors (2 entities)
(5023, 'table', 9, 'MARKETING.LEADS', 'schedule', NULL, 'system', NOW()-INTERVAL'2h 45m', NOW()-INTERVAL'2h 45m'+INTERVAL'6s', NOW()-INTERVAL'2h 45m'+INTERVAL'15s', 2, 1, 'analytics-prod', 'warehouse-prod', 'MARKETING.LEADS', 'MARKETING.LEADS', NULL, 'except_all', ARRAY[]::TEXT[], ARRAY['CREATED_AT'], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Connection reset by peer', '{"type":"ConnectionError"}'::jsonb, 'r5023', 'https://db.com/r5023', '{}'::jsonb, NOW()-INTERVAL'2h 45m'+INTERVAL'15s'),
(5024, 'compare_query', 6, 'Employee Headcount', 'schedule', NULL, 'system', NOW()-INTERVAL'30m', NOW()-INTERVAL'30m'+INTERVAL'5s', NOW()-INTERVAL'30m'+INTERVAL'12s', 4, 3, 'crm-legacy', 'reporting-prod', NULL, NULL, 'SELECT department, COUNT(*) FROM hr.headcount GROUP BY department', 'except_all', ARRAY[]::TEXT[], ARRAY[]::TEXT[], 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Query cancelled by user', '{"type":"CancelledError"}'::jsonb, 'r5024', 'https://db.com/r5024', '{}'::jsonb, NOW()-INTERVAL'30m'+INTERVAL'12s');

-- Summary of Day 5:
-- Succeeded: 12 (entities 1,2,5,7,10,11,14,15,17, queries 1,4,5)
-- Failed - Row Count: 5 (entities 3,8,12,18, query 3)
-- Failed - Diff: 5 (entities 4,6,13,16, query 2)
-- Error: 2 (entity 9, query 6)
-- Total: 24 entities

SELECT 'Seed data loaded successfully!' as status;
SELECT 'Systems: ' || COUNT(*) FROM control.systems;
SELECT 'Datasets (tables): ' || COUNT(*) FROM control.datasets;
SELECT 'Compare Queries: ' || COUNT(*) FROM control.compare_queries;
SELECT 'Tags: ' || COUNT(*) FROM control.tags;
SELECT 'Entity Tags: ' || COUNT(*) FROM control.entity_tags;
SELECT 'Validation History: ' || COUNT(*) FROM control.validation_history;